### ISSUE TITLE
Inventory system is missing

### ISSUE THREAD

**Issue by TimothyLai77** [Wenxuye6/EECS3311-Project#1]
Case #1
Reported by: Timothy Lai
Date Reported: March 16, 2023
Program: GymManagementSystem
Release Number: Iteration 2
Configuration: Java 18.0.1.1 on Windows 11 Pro
Report Type: Requirements Issue
Can Reproduce: Yes
Severity: High
Priority: High

Problem Summary: Iteration 1: Big Story 3. Inventory system doesn’t exist. As an admin I cannot see what equipment exists. 

Problem Description: The big user story 3 from iteration 1 doesn’t seem to be implemented. I can’t find a way to access see/modify the equipment when logged in as the admin page or anywhere else in the app. 

Suggested Fix: Add the inventory system in the admin/manager page.

**Comment by HaochengSun1** [comment]
The inventory system is now available. We created this in iteration 3. Now the administrator shall view equipment’s amount and equipment status.
