### ISSUE TITLE
BMI does not update automatically

### ISSUE THREAD

**Issue by TimothyLai77** [Wenxuye6/EECS3311-Project#2]
Case #2
Reported by: Timothy Lai
Date Reported: March 16, 2023
Program: GymManagementSystem
Release Number: Iteration 2
Configuration: Java 18.0.1.1 on Windows 11 Pro
Report Type: Coding Error
Can Reproduce: Yes
Severity: low
Priority: low

Problem Summary: Member’s BMI is not calculated when height and weight are both filled in. Requires the user to manually fill in their BMI. 

Problem Description: When logged in as a member going into the personal info tab. I would fill out the height and the weight but the BMI still remains at “0.0”. I can enter in the BMI manually but the story in Iteration 1 suggests that this would be automatically calculated for the user. This also occurs when logged in as a coach, front desk, and janitor. 

Suggested Fix: When the user fills out their height and weight the app should automatically fill out the BMI when the changes are confirmed.

**Comment by HaochengSun1** [comment]
Problem fixed. When the administrator add a member to the system, the bmi of this member will be automatically calculated.
