### ISSUE TITLE
Adding courses does not decrease funds

### ISSUE THREAD

**Issue by TimothyLai77** [Wenxuye6/EECS3311-Project#3]
Case #3
Reported by: Timothy Lai
Date Reported: March 16, 2023
Program: GymManagementSystem
Release Number: Iteration 2
Configuration: Java 18.0.1.1 on Windows 11 Pro
Report Type: Coding Error
Can Reproduce: Yes
Severity: High
Priority: high

Problem Summary: Enrolling a course does not deduct the funds from the user’s account. 

Problem Description: When logged in as a member and setting my funds to 100, after adding a course with a cost of 25 the funds value is still 100. Furthermore, there doesn’t seem to be any checks if the member has no money but still tries to add a course. 

Suggested Fix: Before enrolling them in the course just an if-check to see if they have enough money, and if they do deduct it from their account.

**Comment by HaochengSun1** [comment]
We did exactly like you suggested. A membership can only enroll course if he has enough fund. The enrollment will fail if he does not have enough fund
