### ISSUE TITLE
In class schedule: all members have the ability to see and change all other member’s coaches

### ISSUE THREAD

**Issue by TimothyLai77** [Wenxuye6/EECS3311-Project#4]
Case #4
Reported by: Timothy Lai
Date Reported: March 16, 2023
Program: GymManagementSystem
Release Number: Iteration 2
Configuration: Java 18.0.1.1 on Windows 11 Pro
Report Type: Coding Error
Can Reproduce: yes
Severity: High
Priority: High

Problem Summary: All members have the ability to see and change all other member’s coaches. 

Problem Description: If member “A” signs up for a course and selects coach “C1” for that course, member “B” can modify that coach to coach “C2” in the ‘class schedule’ page. It can also end up cluttering the UI since each user would have to look through the entire list and find their name to pick a coach. 

Suggested Fix: Maybe only show the added courses for each member. If a member doesn’t have any added courses it shouldn’t show anything in the ‘class schedule’ page. And if a member does have courses it should only show the courses they picked.

**Comment by HaochengSun1** [comment]
Problem is fixed. Now only the administrator has the power to assign coach to memberships.
