### ISSUE TITLE
Frequently using the type "Object" 

### ISSUE THREAD

**Issue by TimothyLai77** [Wenxuye6/EECS3311-Project#5]
Case #5
Reported by: Timothy Lai
Date Reported: March 16, 2023
Program: GymManagementSystem
Release Number: Iteration 2
Configuration: Java 18.0.1.1 on Windows 11 Pro
Report Type: Design Issue
Can Reproduce: N/A
Severity: high
Priority: high
Problem Summary: Using the type Object in code. 

Problem Description: In various classes the type Object was defined throughout the project. The typing Object is extremely dangerous as the type can be anything, and defies OOP principles. For example, in WorkDAO.java in the getWorkArrayListByName(String account) method, it returns a 2D array of type Object. 

Suggested Fix: I suggest changing the architecture to prevent the use of the Object type.

**Comment by HaochengSun1** [comment]
The code is stable. We want to avoid unnecessary changes since it is too dangerous.
