### ISSUE TITLE
 non-descriptive variable names

### ISSUE THREAD

**Issue by TimothyLai77** [Wenxuye6/EECS3311-Project#6]
Case #6
Reported by: Timothy Lai
Date Reported: March 16, 2023
Program: GymManagementSystem
Release Number: Iteration 2
Configuration: Java 18.0.1.1 on Windows 11 Pro
Report Type: Design Issue
Can Reproduce: N/A
Severity: low/med
Priority: low
Problem Summary: non-descriptive variable names

Problem Description: In various classes in the view package, variable naming should be more descriptive. Naming variables “jtf1”, “jtf2”, “jtf3”, “jtf4”, etc. This substantially hurts maintainability as it doesn’t tell the developer any information about the variable. More evident as there are comments in the initFrame() method (in AddMemberFrame.java) which describe which each variable is. 

Suggested Fix: Change the variable names to be more descriptive in what they represent.

**Comment by HaochengSun1** [comment]
For the comment part, we have gone over all the code and rewrite all the comment. 

For the variables, we don't recognize it as an issue. The code work well and it is stable. Making editions on variables are too risky at this moment.
